# Generated by Django 3.0 on 2020-02-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
